### ISSUE TITLE
Add example for python configuration in documentation

### ISSUE THREAD

**Issue by eileen-kuehn** [MatterMiners/cobald#31]
The documentation for [python configuration](https://cobald.readthedocs.io/en/latest/source/daemon/config.html#python-code-inclusion) currently does not include an example configuration but mentions that at least one `service` needs to be instantiated. Given all the descriptions before it remains unclear what exactly a `service` is in this context.

**Comment by maxfischer2781** [comment]
Closing this since a4662d7 added an example.
