### ISSUE TITLE
Reformulation of pool features

### ISSUE THREAD

**Issue by maxfischer2781** [MatterMiners/cobald#40]
Following the workshop feedback and general sentiment, we should revise the formulation of pool features. Most critically, the wording of ``allocation`` versus ``utilisation`` is too similar to intuitively tell their meaning. However, we might also change ``supply`` and ``demand``while we are at it.

We should at least *rename* the features, but might also change the set of features.

**Comment by maxfischer2781** [comment]
I recommend having one of ``allocation`` and ``utilisation`` have a *positive* connotation and the other a *negative* one. For example, ``used``/``wasted`` or ``vacancy``/``efficiency``. In the one-dimensional case of using the same underlying metric, we'd just have ``used == 1 - wasted`` instead of ``allocation == utilisation``.

**Comment by maxfischer2781** [comment]
Inform @giffels @eileen-kuehn @mschnepf .

**Comment by maxfischer2781** [comment]
Current suggestions:

* `allocation`: `used`, `vacancy`

* `utilisation`: `wasted`, `efficiency`, `fitness`

* `supply`: None

* `demand`: None

**Comment by maxfischer2781** [comment]
Just a heads up @mschnepf that we need to discuss this. ;)

**Comment by mschnepf** [comment]
New suggestions for pool feature names
![COBalD_Metrics_Name](https://user-images.githubusercontent.com/15978823/62375835-80cd0e00-b53f-11e9-8201-36715b9221c6.jpg)

**Comment by mschnepf** [comment]
My preferred renaming:
allocation ->occupancy
utilization -> suitability

**Comment by maxfischer2781** [comment]
I'm fine with "suitability" (with a tie on "fitness"), unless someone has a better suggestion.

In the interest of clear separation, can we agree on an "inverted" naming for "allocation"? "vacancy" has the proper meaning, but most of us seem to associate it with motel rooms...

**Comment by mschnepf** [comment]
I'm still a fan of using both variables with a positive association ( higher number = better).
allocation ->occupancy
utilization -> suitability

Changing also the definition of a feature in addition to rename would cause more work.
Also, I think to have one variable with a positive association and one with a negative association is more confusing.

**Comment by maxfischer2781** [comment]
There hasn't really been any traction on this in a while. It seems that the current naming has been adopted reasonably well by the community.

Should we drop this issue, @giffels @mschnepf @eileen-kuehn?

**Comment by maxfischer2781** [comment]
Closing this since there doesn't seem to be any need nor drive to change what we have right now.
