### ISSUE TITLE
Improve escaping of characters in LineProtocol

### ISSUE THREAD

**Issue by eileen-kuehn** [MatterMiners/cobald#42]
Currently the function `line_protocol` does not take care to correctly [escape some of the characters as demanded by the Line Protocol reference](https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_reference/#special-characters).

In string field values, we must escape

* double quotes
* backslash character

In tags, we must escape

* commas
* equal signs
* spaces

In measurements, we must escape

* commas
* spaces

**Comment by maxfischer2781** [comment]
Closed with #44.
