### ISSUE TITLE
Ignore additional configuration mapping nodes in yaml

### ISSUE THREAD

**Issue by giffels** [MatterMiners/cobald#50]
In order to implement a unified COBalD and TARDIS configuration (see https://github.com/MatterMiners/tardis/issues/79) it is necessary, that the COBalD config parsers ignores unknown yml mapping nodes.

Thanks and best regards,
Manuel

**Comment by maxfischer2781** [comment]
Just checking some older issues. Has this been resolved or are there open tasks for this issue?

**Comment by giffels** [comment]
This has been fixed. I'm closing the issue.
