### ISSUE TITLE
Add citable JOSS paper

### ISSUE THREAD

**Issue by maxfischer2781** [MatterMiners/cobald#81]
In order to stay clearly citable, we should consider providing a contribution to Journal of Open Source Software. See
[example paper](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography).

As per JOSS requirements, this would be a MarkDown paper that is part of the main repository. We could integrate that into the docs.

**Comment by eileen-kuehn** [comment]
Maybe something for the future :) we definitely should go for it at some point of time!
