### ISSUE TITLE
Document publishing process

### ISSUE THREAD

**Issue by maxfischer2781** [MatterMiners/cobald#96]
The publishing process should be documented so that other people can take over if needed.

* Versioning policy according to SemVer
* GitHub/Repo preparation
* PyPI publishing
    * Requires ``wheel``, ``twine``
    * `python setup.py sdist bdist_wheel` to build
    * `twine upload dist/*` to publish

**Comment by giffels** [comment]
I would propose to use GitHub actions to build and upload packages to PyPI. See  https://github.com/MatterMiners/tardis/blob/master/.github/workflows/python-publish.yml for details.
